# Generated by Django 4.2.3 on 2023-10-03 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_ratting_alter_product_color_delete_reviews_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratting',
        ),
    ]
