# Generated by Django 4.2.3 on 2023-10-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_ratting'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='after_discount',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
