# Generated by Django 4.2.3 on 2023-10-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='confirmation_code',
            field=models.IntegerField(null=True),
        ),
    ]
