# Generated by Django 4.2.3 on 2023-09-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_confirmationcode_seller_confirmation_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
        migrations.AlterField(
            model_name='seller',
            name='confirmation_code',
            field=models.IntegerField(max_length=6),
        ),
    ]
