# Generated by Django 4.2.3 on 2023-09-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='confirmation_code',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
